stages:
  prepare_data:
    cmd: python src/prepare_data.py --config params.yaml
    deps:
      - src/prepare_data.py
      - params.yaml
      - data/processed_(A+B)_data.xlsx
      - data/processed_C_data.xlsx
    outs:
      - data/train_(A+B).csv
      - data/test_C.csv
